name = "gtap9_in_julia"
uuid = "ae7eb498-69c5-411d-a1c9-db3c579f0cd0"
authors = ["mitchphillipson <mitch.phillipson@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MPSGE = "d5dc2f44-7ae2-49e9-bc77-b47b6bca565d"

[compat]
DataStructures = "0.18.22"
JLD2 = "0.5.13"


[sources]
MPSGE = {url = "https://github.com/julia-mpsge/MPSGE.jl", rev = "indexed_nests"}